### ISSUE TITLE
export fine grained information about BU blocking in machine readable format

### ISSUE THREAD

**Issue by andreh12** [mommsen/evb#9]
Similar to adding detailed information about why a BU is in blocked etc. state as done in commit e7a2659 in human readable format, the BU could export (e.g. in an additional flashlist column) the same format in an easily parseable format such as a comma separated list of keywords.

For example `RAMDISK_FULL,TOO_MANY_LS_QUEUED_FOR_FUS` etc.

**Comment by mommsen** [comment]
Hi @andreh12,

here's the full list of keywords which will become available in the next version of the EvB:

RAMDISK_TOO_FULL
RAMDISK_USAGE_HIGH
NOT_ENOUGH_FUS
NO_FUS_AVAILABLE
ALL_FUS_QUARANTINED
ALL_FUS_STALE
HLT_OUTPUT_HIGH
HLT_OUTPUT_TOO_HIGH
MANY_LS_QUEUED_FOR_FUS
TOO_MANY_LS_QUEUED_FOR_FUS
TOO_MANY_LS_QUEUED_ON_FUS
RESOURCE_SUMMARY_FAILURE
RESOURCE_SUMMARY_STALE

Let me know if you have suggestions about a different naming. Note that some of these keywords will cause the BU to block all requests, others may only cause the BU to throttle. 

These keywords will be exported in the BU flashlist as a csv in statusKeywords. This could look like this:
statusKeywords: NOT_ENOUGH_FUS,MANY_LS_QUEUED_FOR_FUS
statusMsg: Throttling requests because there are only 16 FU slots available. In addition, there are 16 quarantined FU slots, and there are 2 LS queued for FUs which is above the low water mark of 1 LS

Remi

**Comment by andreh12** [comment]
Hello @mommsen ,

the keywords are fine with me. The only potential comment I would have is if you would think it would be useful to prefix or postfix them with `BLOCKING_` or `THROTTLING_` if they are causes of blocking or throttling (e.g. in case we want to give higher priority to causes for blocking to be displayed). On the other hand, we should have this information (blocking/throttling) already in the BU state.

**Comment by mommsen** [comment]
Hi @andreh12,

I was actually considering this. It would work for the blocking cases. However, the throttling cases are not as clear cut: multiple throttling cases can cause the BU to go to blocked state, or if the BU is not loaded, a single throttling case may not yet prompt the BU to change its state to Throttled. Thus, I would rather rely on the state information.

Remi

**Comment by mommsen** [comment]
Implemented in version 5.4.2.
